name: 'Create release'
description: 'Creates a release using the GitHub API'
inputs:
  token:
    description: 'The GitHub token used to authenticate with the GitHub API.'
    required: false
  tag-name:
    description: 'The name of the tag.'
    required: true
  target-commitish:
    description: 'The commitish value that determines where the Git tag is created from.'
    required: false
  name:
    description: 'The name of the release.'
    required: false
  body:
    description: 'Text describing the contents of the tag.'
    required: false
  draft:
    description: 'true to create a draft (unpublished) release, false to create a published one.'
    required: false
    default: false
  prerelease:
    description: 'true to identify the release as a prerelease. false to identify the release as a full release.'
    required: false
    default: false
  discussion-category-name:
    description: 'The name of the discussion category for this release.'
    required: false
  generate-release-notes:
    description: 'true to generate release notes for the release based on the comparison between the tag specified by tag-name and the tag specified by the default-branch. false to use the body as the full release notes.'
    required: false
    default: false
  make-latest:
    description: 'Specifies whether this release should be set as the latest release for the repository.'
    required: false
    default: false
outputs:
  id:
    description: 'The ID of the release'
  node-id:
    description: 'The Node ID of the release'
  url:
    description: 'The URL of the release'
  html-url:
    description: 'The HTML URL of the release'
  assets-url:
    description: 'The URL of the release assets'
  upload-url:
    description: 'The URL to upload release assets to'
  tarball-url:
    description: 'The URL of the release tarball'
  zipball-url:
    description: 'The URL of the release zipball'
  tag-name:
    description: 'The name of the tag that was created'
  target-commitish:
    description: 'The commitish value that determines where the Git tag is created from'
  name:
    description: 'The name of the release'
  body:
    description: 'Text describing the contents of the tag'
  draft:
    description: 'true if the release is a draft (unpublished) release, false if the release is published'
  prerelease:
    description: 'true if the release is identified as a prerelease release, false if the release is identified as a full release'
  created-at:
    description: 'The date and time the release was created'
  published-at:
    description: 'The date and time the release was published at'
runs:
  using: 'node16'
  main: 'dist/index.js'
