name: 'Create release'
description: 'Creates a release using the GitHub API'
inputs:
  tag_name:
    description: 'The name of the tag.'
    required: true
  target_commitish:
    description: 'The commitish value that determines where the Git tag is created from.'
    required: false
  name:
    description: 'The name of the release.'
    required: false
  body:
    description: 'Text describing the contents of the tag.'
    required: false
  draft:
    description: 'true to create a draft (unpublished) release, false to create a published one.'
    required: false
    default: false
  prerelease:
    description: 'true to identify the release as a prerelease. false to identify the release as a full release.'
    required: false
    default: false
  discussion_category_name:
    description: 'The name of the discussion category for this release.'
    required: false
  generate_release_notes:
    description: 'true to generate release notes for the release based on the comparison between the tag specified by tag_name and the tag specified by the repository's default_branch. false to use the release's body as the full release notes.'
    required: false
    default: false
  make_latest:
    description: 'Specifies whether this release should be set as the latest release for the repository.'
    required: false
    default: false
outputs:
  id:
    description: 'TODO'
  node_id:
    description: 'TODO'
  url:
    description: 'TODO'
  html_url:
    description: 'TODO'
  assets_url:
    description: 'TODO'
  upload_url:
    description: 'TODO'
  tarball_url:
    description: 'TODO'
  zipball_url:
    description: 'TODO'
  tag_name:
    description: 'TODO'
  target_commitish:
    description: 'TODO'
  name:
    description: 'TODO'
  body:
    description: 'TODO'
  draft:
    description: 'TODO'
  prerelease:
    description: 'TODO'
  created_at:
    description: 'TODO'
  published_at:
    description: 'TODO'
runs:
  using: 'node16'
  main: 'dist/index.js'
