name: Create release

on:
  push:
    tags:
      - '*'
  create:
    tags:
      - '*'

jobs:
  build:
    name: Create release
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: dae-ne/create-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
