name: Update tags

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'specific version'
        required: false
        type: string
      update-type:
        description: 'version update type'
        required: false
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  update-tags:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          submodules: true
      - name: Set up Git
        run: |
          git config user.email '${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com'
          git config user.name '${GITHUB_ACTOR}'
      - name: Add permissions
        run: |
          chmod +x update-tags-script/update_tags.sh
      - name: Run script
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          if [ -z "${{ github.event.inputs.version }}" ]; then
            update-tags-script/update_tags.sh -f -t ${{ github.event.inputs.update-type }}
          else
            update-tags-script/update_tags.sh -f -v ${{ github.event.inputs.version }} -t ${{ github.event.inputs.update-type }}
          fi
        shell: bash
